opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - unneeded_parentheses_in_closure_argument
  - operator_usage_whitespace

empty_count:
  severity: warning

line_length:
  # warning: 120
  warning: 200

type_body_length:
  # error: 350
  error: 500

identifier_name:
  min_length: 0


excluded:
  - Carthage
  - Pods

reporter: "xcode"
